name: API Proxy

on:
  push:
    branches:
      - main  # Run this when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the latest LTS version

      - name: Install Dependencies
        run: npm install  # Assuming you have a package.json file for dependencies

      - name: Start Proxy Server
        run: |
          echo "const express = require('express');" > server.js
          echo "const request = require('request');" >> server.js
          echo "const app = express();" >> server.js
          echo "const PORT = process.env.PORT || 3000;" >> server.js
          echo "const API_KEY = process.env.API_KEY;" >> server.js
          echo "app.use('/api', (req, res) => {" >> server.js
          echo "  const url = 'https://your-api-endpoint.com' + req.url + '?key=' + API_KEY;" >> server.js
          echo "  req.pipe(request(url)).pipe(res);" >> server.js
          echo "});" >> server.js
          echo "app.listen(PORT, () => console.log('Server running on port ' + PORT));" >> server.js

      - name: Start the Server
        run: node server.js
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Use the secret here
